version: "3.9"

services:

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    depends_on:
      - redis
      - db

  redis:
    image: redis:7

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: saas
      POSTGRES_PASSWORD: saas123
      POSTGRES_DB: saas_db
